- src/extension.ts
Fix #2 
But the "Download settings" when nothing is configured yet (On a new setup for example) is still not working as before the modification, once this is fixed, everything should work fine.
> Add OS X and Linux compatibility

- src/pluginService.ts
Previously only attempting to use Window's specific USERPROFILE env variable to determine home directory, *nix variants use HOME. This allowed the extension to work on OSX for me and should allow the extension to continue working properly on Windows.
Attribution: Method for determining home directory came from this Stack Overflow answer: http://stackoverflow.com/a/9081436
> Cross platform method of determining homedir

- README.md
Hotkey in readme is incorrect, command palette shows it as "Shift + Alt + u/d" not "ctrl + alt u/d".
You have to type ">" before sync in order to download/upload, which takes you from the main command palette screen to "show and run commands".
> Fixed shortcuts / added details in readme

- src/extension.ts
- src/pluginService.ts
Use ExtensionContext to detect extension path and decide whether we're using default VS Code instance or Insiders version.
#11
> detect VS Code - Insider version

- src/extension.ts
> Spell corrected

- src/githubService.ts
Hi there. I had an API failure to upload when trying to use the extension in a clean VS Code install. I dug into it and fixed the error, this is my commit message:
Github API fails when one of the default files is sent without any content (ie an empty string). This fixes a bug where a user will get a failure message from the Github API if one of these four default files has not been created by VS Code beforehand.
A disadvantage to this fix is that VS Code provides some good default templates when it creates a file, giving some instruction to the user. Having an existing non-empty file already downloaded will prevent this nice behavior. I think a better fix would be to have GIST_JSON_EMPTY actually be empty of files - I leave that to the repository owner to decide.
> Add default empty content to uploaded files

- src/commons.ts
Several things to note:
- When the input box loses focus it closes, and the promise resolves with `undefined`. We simply reopen the input box if that is the case.
- When the user genuinely wants to close the wizard (by pressing escape), the promise resolves with undefined. Since we have no way of telling if this value `undefined` is because the user has cancelled the wizard or because the editor has lost focus, we have to assume the editor has lost focus (because that's what happens when we open the GitHub link).
- So how does the user genuinely close the wizard? We allow the user to cancel the wizard by typing `esc` and pressing enter. We check for this value and do not reopen the input box if this was what the user typed.
> Fix issue with input closing when losing focus

- src/environmentPath.ts
- src/extension.ts
- src/githubService.ts
The keybindings file was always being set to keybindings.json because
of missing braces. In addition, there were some inconsistencies
between files on what the name of the Mac keybinding filename was.
keybindingDefault is removed from the creation snippet as it should
just be using keybindings.json. Lastly, to prevent settings overrides,
we no longer clear files from the gist when the filename begins with
"keybindings".
> fix mac-specific keybinding sync

- src/extension.ts
I noticed I started getting the message "No extension need to be installed" every time VScode started. This message does not give any value, and is kind of annoying, so I removed it.
> Remove unnecessary info message

- src/commons.ts
- src/environmentPath.ts
Fixes #90.
Switches to an actual file that is created on demand, and recreated every time a sync (that results in changes) is performed.
Using an actual file has the beneficial side effect of being able to save it and thereby mark it as clean, so that no prompt for saving is shown on exiting VSCode.
> Cross platform sync summary fix

- src/extension.ts
A missing keybindings.json file is now tolerated on Windows, and a missing keybindingsMac.json file on macOS.
> Fix for #117

- src/githubService.ts
- src/util.ts
Allows extension to use the HTTP_PROXY environmental variable when the http.proxy setting is not defined in VS Code's User settings.  Closes Issue #126
> Fallback to system defined proxy. Issue #126

- package.json
- src/githubService.ts
- src/setting.ts
https://github.com/shanalikhan/code-settings-sync/issues/67
This commit adds support for GitHub Enterprise.
I did not edit the README file because I realized that the config instructions were in a blog post.
Let me know what you think, thanks!
> add GHE support

- src/util.ts
Check for port being not-null in the parsed URL prior to making a request.
Passing in a null port causes node to connect with SSL on the wrong port.
Fixes #263
> Add check for port in http options

- src/setting.ts
In additition to the git project cache, Project Manager can also create cache files with `vscode` and `svn` names. This change adds these files to the default ignore list.
In addition, this change adds the Git Project Manager files to the default ignore
The Git Project Manager uses `gpm_projects.json` and `gpm-recentItems.json` files to store the cached list of projects.
These should be excluded by default for anyone using this extension.
The Git Project Manager extension is here: https://marketplace.visualstudio.com/items?itemName=felipecaputo.git-project-manager
> Update Project Manager default ignore files.

- src/extension.ts
I do not see the point of the var teims. Instead of fixing the typo i removed it and just let the promise call since i didn`t find the var being used or passed anywhere. Are we actually using it? If so i can change this PR to just fix the typo
> Remove unused var. Closes #424

- README.md
I added the flow of the Upload and Download commands in gifs to the README, as requested in issue #423.
> Add upload and download gifs to readme (issue #423)

- src/pluginService.ts
Replace the unreliable check for `packageJSON.__metadata` (not present in `insiders`) with `extensionPath`.
This is to address #428
> Fix insiders build fails to get extension list

- README.md
syncLocalSettings.json file path on Linux is wrong in README file.
This will fix it.
> Fix syncLocalSettings path on Linux

- src/environmentPath.ts
Looks like `environmentPath.ts` is looking for a specific path "/Code" ( or "/Code - Insiders"). For me, this path doesn't exist since I'm using the open-source version of VS Code, thus the path which should be looked for is "/Code - OSS". I don't know if any other changes in other files should be made, but this seems to work.
> Added support for "Code - OSS"

- src/environmentPath.ts
This resolves #510 by explicitly testing for the OSS version of vscode when constructing the config and plugin paths.
> Resolves #510 - support OSS build of vscode

- src/environmentPath.ts
This PR adds support too freedesktop XDG_DATA_HOME and XDG_CONFIG_HOME environment variables on linux platforms. This can be useful if VScode was installed for example from flatpak as config dir is in ${HOME}/.var/app/com.visualstudio.code/code/config and extensions are located at ${HOME}/.var/app/com.visualstudio.code/data/vscode/extensions.
> add support for xdg environment paths

- src/extension.ts
Hi @shanalikhan , I just installed your plugin in VSCode 1.23.0 with Ubuntu 16.04 64-bit OS. 
**Step to reproduce:**
1. Install Code Settings Sync plugin.
2. Open Command palette using Ctrl + Shift + P.
3. Click `Sync: How to Configure`
**Expected behaviour:**
It will open browser to the 'How to configure' link.
**Actual Behaviour:**
When I click the **How to Configure** from the command palette, the VSCode return  `[UriError]: Scheme contains illegal characters.`.
After that, I forked your source code and find what's the problem that cause the error. Finally, I found it and fix it. Hope the fix is right and not conflict with others. Thank you for the plugins. :+1:
> Fix uri string typo on 'How to configure' executeCommand action.

- README.md
- src/commons.ts
- src/extension.ts
- src/setting.ts
- tsconfig.json
Added functionality for users to define extensions to be ignored through syncLocalSettings.json - any extension names will be ignored when syncing up and down.
> Ignore extensions

- src/sync.ts
I found small mistake.
The same message was displayed.
https://github.com/shanalikhan/code-settings-sync/blob/da101e3dd0e9dea395434f142af518c110871851/src/sync.ts#L812-L820
> Corrected the message to be displayed

- CONTRIBUTING.md
- README.md
The hrefs inside README.md and CONTRIBUTING.md were set to graphs/contributors which directs to a non-existent page (https://github.com/shanalikhan/code-settings-sync/blob/master/graphs/contributors)
I have changed both to point to https://github.com/shanalikhan/code-settings-sync/graphs/contributors instead.
> Update non-functional link in README.md

- src/util.ts
Downloaded extensions fails to extract to the temporary folder.
The first argument of temp.mkdir method does not take a path. It takes an affix for the created folder name. If you leave the affix as undefined (or anything falsy), it will defaults to 'd-' and create and return (a promise of) the full path of a folder that gets the name 'd-' + todays date + process Id + a random number.
**Fixes**: #642
> Fix for temp.mkdir returning double paths #642

- src/commons.ts
- src/environmentPath.ts
- src/sync.ts
This adds support for the Coder.com VS Code Cloud IDE.
- Added the property `isCoderCom` to `Environment`
- Added some setting overrides in a few places to settings that work for Coder.com
- Force disable XDG home on Coder.com
- Remove `.` in configSuffix
- Force set the settings base path to `/tmp`, which resolves to `/tmp/User`
- Force manual installation of extensions rather than using the CLI
- Fixed an unrelated TS lint issue so it would pass the linter
**Fixes**: #714
I tested the plugin on regular VS Code on a Windows machine with a simple settings.json file and 3-4 extensions. The settings file was uploaded from the Windows box and then downloaded into the Coder.com VS Code Cloud IDE using the extension, which worked. The synced extension installations worked as well.
I also …
> Add support for Coder.com (#714)

- .vscode/launch.json
- package.json
- src/commons.ts
- src/localize.ts
- webpack.config.js
This PR improves extension startup time by bundling with webpack. On my local environment startup is down to 400 - 500 ms in the "Running Extensions" view. 
I would love to be able to compare Javascript profiles of before and after but  I don't know how to profile extension startup time in vscode. 
**Fixes**: #656 
I was able to build the extension using the npm scripts including compile, watch, and vscode:prepublish. I tested the changes on my environment and was able to download my settings stored in github gist. 
My environment: windows 10; vscode 1.29.1 (user setup)
> Add webpack bundling for faster startup

- src/environmentPath.ts
This change seems too simple to me, so I wouldn't find someone else looking over it before merging. I'm wondering, why the extension was set to save to application support in the first place when in portable mode, especially if all other OS's were set to save to VSCODE_PORTABLE?
This attempts to resolve #684, support portable version on mac
- When in portable mode, macs environment operates the same as other OS's. That is, it writes to VSCODE_PORTABLE instead of application support.
I believe this is the proper behavior, as while portable we don't want any data to be saved to any part of the fine system other than the portable directory.
Tested on VSCode 1.29.1, running the latest clone of code-settings-sync
macOS 10.14.2, MacBookPro11,3.
Tested initial gist creation, successful settings …
> NOMERGE: Always use VSCODE_PORTABLE env when portable

- package.json
- src/localize.ts
As discussed in #717 I fixed the issue with the commands not being correctly translated.  It looks like the root path of the extension wasn't being set correctly. 
I packaged the extension with `vsce package` and installed it on my machine with `code --install-extension`. The Advanced Settings menu is now appearing correctly.
> Fix loading language bundles and add missing dependencies

- .gitignore
Remove one of `package-lock.json` from `.gitignore`.
- Fix duplicate gitignore setting
**Fixes**: # none
none
none
> Fix duplicate gitignore setting

- install_local.txt
- package.json
- src/commons.ts
Fix "Extension host terminated unexpectedly" in Visual Studio Code v1.31.0 with Settings Sync.
( https://github.com/Microsoft/vscode/issues/64981 )
```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
Referenced from: /Users/xxx/.vscode/extensions/shan.code-settings-sync-3.2.5/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
Expected in: flat namespace
```
It causes by `fsevents`, also `chokidar`.
https://github.com/Microsoft/vscode/issues/65335
So, I remove `chokidar` from this repository, and use **[FileSystemWatcher](https://vshaxe.github.io/vscode-extern/vscode/FileSystemWatcher.html)** . …
> Avoid using chokidar (Fix #762)

- CHANGELOG.md
Correct the wrong year of release date for v3.2.5 in CHANGELOG
- Correct the wrong year of release date for v3.2.5 in CHANGELOG
**Fixes**: #
Only documentation updated, no need to be tested
> Correct the wrong year of release date for v3.2.5 in CHANGELOG

- src/service/pluginService.ts
Solves the issue #756 caused by a hardcoded extension dir.
This is a temporary workaround and we should use the env variables to check a valid extension dir instead of hardcoded ones:
- The `extensionDir` variable was changed to `.vscode/` to prevent the sync of "something" with `.vscode` in its name. (ex: `bung87.vscode-gemfile`)
https://github.com/chase9/code-settings-sync/blob/36461174f534fefc4bce03a6f4ca182090287360/src/service/pluginService.ts#L12
- The `extensionDirPortable` variable was changed to `/extensions/` because the path for the extensions folder in a portable VSCode instance, is `extensions`
https://github.com/chase9/code-settings-sync/blob/36461174f534fefc4bce03a6f4ca182090287360/src/service/pluginService.ts#L13
Ref to `extensions` path in vscode: …
> fix(extensions): change portable extensions dir

- src/environmentPath.ts
This removes disabling of TLS certificate validation, which side effects into any other process running within VS Code. 
This closes #776 
If any users report SSL trust issues, they need to fix the issue with VS Code in general, and it should not be handled by an extension. More information on how to properly trust certificates can be found here: https://code.visualstudio.com/docs/setup/network#_ssl-certificates
_Edit:_ Worst case, _the user with the issue_ can turn it off in VS Code if they wish with `--ignore-certificate-errors`, but it should **not** be the default for everyone.
> Remove Disabling of TLS Certificates

- src/service/githubService.ts
Octokit deprecation warnings
- `headers` is deprecated and we shouldn't use it.
- `rejectUnauthorized` set to false is a security issue, and we shouldn't bother to find a workaround for it.
https://github.com/shanalikhan/code-settings-sync/blob/f698ce9112d7d80b3db21b71674feed0475307b3/src/service/githubService.ts#L49
- The `authenticate` function is deprecated and we should use the `auth` option in the constructor of Octokit.
https://github.com/octokit/rest.js#authentication
Tested with "Launch extension" and `autoUpdate` on and off.
> fix(github): fix octokit warnings

- src/service/pluginService.ts
This solves #756.
- Remove the gallery installation check, because isn't a good validation (It can be "bypassed" and just adds complexity. In the worst-case scenario, the extension will not be installed.
**Fixes**: #756 
Tested with "Launch extension" and `autoUpdate` on and off.
> fix: remove gallery installation check

- src/sync.ts
Fix a bug where it wasn't correctly ignoring folders if there was more than 1 folder in the list.
- change filter to fit function definition -- check if a file has a *matched* ignoreFolder
**Fixes**: #
Add folder to ignored folder list. Check files are properly ignored.
Before Fix:
After Fix:
> fix bug in ignoreUploadFolder

- src/commons.ts
Saves the custom settings file in a user friendly, easy to read / write format.
Instead of a humungous 1 liner, quality of Life changes for when you're editing the local config.
- Change spacing format of syncLocalSettings.json
None, no need for testing since it's built into stringify.
Ugly Settings:
Pretty Settings:
> prettify custom setting json

- package.json
- src/commons.ts
- src/service/autoUploadService.ts
- src/service/fileService.ts
- src/service/pluginService.ts
- src/setting.ts
- src/sync.ts
This PR fixes auto-upload by using Chokidar and `vscode.extensions.onDidChange` instead of `vscode.FileSystemWatcher`, which only works on files in the current workspace.
- Use Chokidar instead of `vscode.FileSystemWatcher` to detect changes in user settings
- Use VSC's onDidChange event to check for changes in extensions
- Unlock lock file when returning from the `StartWatch()` function after locking to prevent it from becoming unusable
**Fixes**: 3
I have tested it by installing/uninstalling extensions and modifying my settings. I can confirm that the changes don't affect any other areas in the code, and it uploads and downloads successfully.
> Fix auto upload

- .vscodeignore
This PR decreases the size of the VSIX file to ~150KB
- Ignore node_modules and some other unnecessary folders from build
**Fixes**: 1
I have tested this by ignoring the folders, building the extension, and installing it locally.
> Decrease production file size (#823)

- src/pragmaUtil.ts
Fixed a bug where there was 3 empty lines at the top of settings.json if there was no ignoredBlock
**Fixes**: #819
> check for empty ignoredBlock

- src/commons.ts
- src/sync.ts
This resolves issues with autoUploadService being undefined when using its methods.
- Add new methods to make sure that autoUploadService is set
- Initialize autoUploadService before calling functions if not set
**Fixes**: #832 
Tested by @ActionCactus
> Make sure that autoUploadService is set before using it

- package.json
- src/service/autoUploadService.ts
- webpack.config.js
This PR adds `vscode-fsevents` as an external in the webpack configuration file so webpack can properly compile the new changes.
- Add `vscode-fsevents` to externals
**Fixes**: #834's warning
Built extension and didn't get warning
> Fix warning from webpack [vscode-fsevents]

- README.md
use URL query string to automatically select gist and add a description
now can generate the token just by one click
- just let lazy people like me make fewer efforts
- maybe you should change the photo of README
**Fixes**: # None
only docs changed
> docs: make generating token more user-friendly

- .vscode/launch.json
- .vscode/tasks.json
Now Tests can be run by:
1. Clone repo
2. `cd path/to/code-settings-sync && npm install && code .`
3. `Launch Extension` by pressing `F5`
4. From Debugger menu, start `Launch Tests`
**Fixes**: #841 
By running the tests using above steps :P
> Updated to task api 2.0.0 and fixed tests

- src/pragmaUtil.ts
- src/setting.ts
- src/sync.ts
- Regx for `opensCurlyBraces` is changed
- Variable name are made more generic
- Same functions are used for `keybindings.json` which were used for `settings.json`
**Fixes**: #800 #515 
- Manually used for syncing my settings.
- Testing using `Launch Tests` was failing before any new changes. We need to fix them.
> Utilized pragmaUtil Functions for kb.json file

- src/pragmaUtil.ts
- Modified the toggleComments function to help go along with the format of the user's settings (e.g. spaces (amount) or tabs).
- Included fix by @ioprotium for [#865](https://github.com/shanalikhan/code-settings-sync/issues/865)
> Cleaned up toggling commented settings

- configs/webpack.config.js
The package `clean-webpack-plugin` was recently updated to use newer syntax, and this broke the webpack configuration. This PR fixes issues with building the extension because of the update. 
Change 
```
const CleanWebpackPlugin = require("clean-webpack-plugin").default;
```
to
```
const { CleanWebpackPlugin } = require("clean-webpack-plugin");
```
> Fix issues with webpack

- src/service/pluginService.ts
Format `pluginService.ts` to prevent `tslint-check` from failing. 
- Format `pluginService.ts`
> Format pluginService.ts to fix tslint-check

- src/service/pluginService.ts
- src/sync.ts
This PR fixes issues that prevented extensions from being synced properly.
- Properly throw an error when one occurs
- Scan for missing extensions correctly
> Fix issues with extension sync

- src/service/pluginService.ts
Install extensions in order to sync `INSTALLING` and `INSTALLED` messages.
- Use synchronous code to loop through the list and install extensions
> Install extensions in order

- src/sync.ts
This PR fixes an issue that could cause the download to fail if an error occurred during the extension installation process.
- Throw error instead of setting `addedExtensions` to it.
**Fixes**: #912 
#912
> Properly throw errors

- src/extension.ts
- src/localize.ts
This PR uses `locale.json` to resolve the locale instead of environmental variables. This leads to better consistency in localizations.
- Use `locale.json` as config for `localize.ts`
**Fixes**: #886 
Tested by changing language and watching as the extension properly localizes it.
> Resolve locale properly

- src/commons.ts
- src/sync.ts
This PR fixes issues that would occur on the first install of this extension.
- Return default `customConfig` if it's not set yet
- Check if a file exists before reading it
Tested by debugging extension.
> Fix issues on first install

- src/service/github.service.ts
- src/sync.ts
This PR adds more understandable errors for `@octokit/rest`.
- Catch errors and show more understandable messages if gist id is incorrect.
**Fixes**: Every issue with `HttpError: Not Found`
Tested by inputting fake gist id and checking for the custom error. Also doesn't break anything if gist id is correct.
> More understandable errors for @octokit/rest

- package.json
- src/service/file.service.ts
- src/sync.ts
Fixes syncing of snippets.
- Use `recursive-readdir` to find files to upload
- Add all files found to `allSettingFiles` instead of just `settings.json` and `keybindings.json`
**Fixes**: #927 
Tested by uploading and checking for snippets.
> Fix Snippet Sync

- configs/webpack.config.js
- package.json
This PR fixes issues with modules not being bundled.
- Stop using `webpack-node-externals`
- Ignore the warning from express
Tested by building and installing extension VSIX file.
> Fix webpack build process

- src/sync.ts
This PR only shows the "Gist newer" dialog if `lastUpload` isn't null
- Check if `lastUpload` is null
> Fix Safe Upload

- src/service/webview.service.ts
- ui/landing-page/landing-page.html
This PR adds a button to the landing page to download public gist.
- Add button to landing page
- Ask for gist id when clicked, and save it
- Enable `downloadPublicGist`
**Fixes**: https://github.com/shanalikhan/code-settings-sync/pull/876#issuecomment-507641582
> Add Button to Download Public Gist

- src/localize.ts
This PR fixes a **CRITICAL** issue in `localize.ts` that would cause the extension to crash. In a previous PR, I used `Array.flat()` to make sure the localization arguments were not nested arrays, but this caused many issues with VSCode and somehow got past my testing.
- Don't use `Array.flat()`
@shanalikhan This is a very important fix. It should be merged as soon as possible into `v3.4.0`.
> Fix issue with Localize

- src/sync.ts
The settings being saved would potentially overwrite `forceUpload` being set to true. This PR solves this by modifying the object that is used to save settings at the end.
- Modify `syncSetting` instead of `localConfig.extConfig` because it is used at the end of the process in `state.commons.SaveSettings()`.
> Fix issue with forceUpload

- src/service/webview.service.ts
- src/sync.ts
- ui/landing-page/landing-page.html
- ui/landing-page/landing-page.js
- ui/shared/styles.css
This PR adds a button to not show the landing page, even if the extension is not configured.
- Use `context.globalState` to keep track of preference
- Reset the preference when resetting extension settings
- Don't show the landing page if enabled
**Fixes**: https://github.com/shanalikhan/code-settings-sync/issues/959#issuecomment-511682067
> Landing Page: Don't Show This Again

- src/service/webview.service.ts
- ui/gist-selection/gist-selection.js
This PR improves the UX of Settings Sync
- If no gists are available, tell the user to skip and upload
- Properly download after selecting gist
**Fixes**: https://github.com/shanalikhan/code-settings-sync/pull/969#issuecomment-513135826
> Improve UX Further

- CONTRIBUTING.md
- README.md
- ui/landing-page/landing-page.html
Just a few minor typo fixes: `Github` -> `GitHub`.
It would be great if this could be fixed in the repo description as well:
> Fix GitHub spelling

- README.md
The extension works just as well on Mac, we might as well be explicit about how macOS users are to interact with it.
Add macOS shortcuts to the README file.
n/a
n/a
> Add macOS shortcuts to README

- src/service/github.service.ts
- src/sync.ts
Allows uploading settings without forcing when multiple machines are uploading settings.
Example failing scenario:
- Machine A uploads settings to cloud
- Machine B downloads these settings
- Machine B changes settings and uploads them to the cloud
- Machine A downloads the settings
- Machine A changes settings and tries to upload them
The last upload attempt fails because A's last upload time is before the cloud's last upload time, even though A downloaded the settings.  A forced upload is needed in order to upload the settings.  It, therefore, makes sense to compare against the local download time.
- Change IsGistNewer to compare the gist upload time to the local download time
- On an upload, set the local download time to the same upload time
- Fix bug with the check to see if files …
> Safe upload
