src/extension.ts
fix this issue: https://github.com/shanalikhan/code-settings-sync/issues/6
=> fix PATH for linux

src/extension.ts
For a smaller diffs and improved readability of what has been changed
=> Pretty-print and sort extensions

package.json
=> Minor typo in advanced options

src/githubService.ts
=> Use VSCode proxy settings

src/commons.ts
=> Remove summary trailing whitespaces

README.md, package.json, src/commons.ts, src/environmentPath.ts, src/extension.ts, src/githubService.ts, src/setting.ts
Fixing https://github.com/shanalikhan/code-settings-sync/issues/168
https://github.com/shanalikhan/code-settings-sync/issues/180
=> Anonymous gist

src/commons.ts
=> fixed typo

src/commons.ts, src/extension.ts
=> Mac keybindings

README.md, package.json, src/commons.ts, src/environmentPath.ts, src/extension.ts, src/fileManager.ts, src/setting.ts
=> Ignore settings

src/extension.ts
Fix #320, according to 914b440
=> Dispoing all the status bar message, fix #320

src/commons.ts
=> do not write `syncLocalSettings.json` if file has no change.

README.md
Depends on updated images from https://github.com/shanalikhan/shanalikhan.github.io/pull/1
=> Update README to reflect new GitHub settings page

package-lock.json, src/extension.ts
Fixed from "Preserve Setting to stop overide after Download" to "Preserve Setting To Stop Override After Download".
=> Fix menu capitalization and typo

README.md
Size of the README gifs reduced as requested in #430.
=> Compress README gifs

src/pluginService.ts
Changed info.publisher from publisherDisplayName to publisher.
=> Fixed #394 issue

README.md
I think this makes it a bit harder to get confused with token and Gist ID. Not sure if it's correctly worded. 
Also, standartized periods on bold lines and headings, where applicable,
=> small clarification

src/extension.ts
Allows 'false' values to be set in syncLocalSettings.json
=> Fix for #516

README.md
let me know if i did something wrong
=> readme: fixed typos

PULL_REQUEST_TEMPLATE.md
I corrected `Github` -> `GitHub` in the pull request template.
PS: I did not use the pull request template on this pull request as this is too simple to need an advanced description.
Have a nice day :)
=> Corrected a typo

CONTRIBUTING.md
- Changes in `CONTRIBUTING.md`
=> Added documentation for tests in CONTRIBUTING.md

ui/gist-selection/gist-selection.js
This PR sorts the gists from most recent to oldest.
- Sort gists from most recent to oldest.
=> Sort Gists

src/extension.ts, src/localize.ts, src/models/language-pack.model.ts
This PR improves localization.
- Use the `VSCODE_NLS_CONFIG` environmental variable to detect the locale
- Use more modern code to find and read the proper localization file
- Auto initialize to provide localization services very quickly
Tested by using the default locale (en), a different one, and an invalid locale. All of these scenarios are handled properly.
=> Improve Localization

src/commons.ts, src/service/github.oauth.service.ts, src/service/webview.service.ts, src/sync.ts, ui/gist-selection/gist-selection.html, ui/gist-selection/gist-selection.js, ui/landing-page/landing-page.html, ui/landing-page/landing-page.js
This PR improves the UX of Settings Sync
- ...https://github.com/shanalikhan/code-settings-sync/pull/960#issuecomment-512782903
- Bind checkbox to state
**Fixes**: https://github.com/shanalikhan/code-settings-sync/pull/960#issuecomment-512782903
- Download without config (no skip button, download initiated after gist selected)
- Upload without config (skip button, upload initiated after gist selected or skipped)
- Checkbox binding checked by changing the state and reopening the page
=> Improve UX
